name: Email Activity Monitor

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '*/15 * * * *'  # runs every hour

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Restore token.pickle
        run: |
          echo "${{ secrets.GMAIL_TOKEN_BASE64 }}" | base64 --decode > token.pickle

      - name: Run email monitor script
        run: |
          python main.py

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add result/log.xlsx
          git commit -m "Update log.xlsx" || echo "No changes to commit"
          git push
